### ISSUE TITLE
config.inc.php not found 

### ISSUE THREAD

**Issue by arthuragnar** [inclusive-design/AChecker#53]
I am installing Achecker but while installation I am getting error "../include/config.inc.php not found ". 
So I created an empty file named config.inc.php but I am still getting that error. So I checked the codebase  but couldn't find "config.inc.php" . Please add config.in.php.

**Comment by cindyli** [comment]
The readme on the AChecker github home page https://github.com/inclusive-design/AChecker says:

_Note, if you are installing from a Git clone of AChecker, before following the instructions above, you will need to create an empty configuration file. In the AChecker directory, at the command prompt issue the following command:

touch include/config.inc.php_

Also, please make sure the file permission of `include/config.inc.php` is set to be writable by AChecker installer. The permission mode 755 usually works well.

**Comment by arthuragnar** [comment]
I am using windows,  so touch is not working. I have already created 'config.inc.php' .

**Comment by cindyli** [comment]
1. Make sure `config.inc.php` is created at the correct location in the `include` directory within your AChecker root;
2. File permission again.
