### ISSUE TITLE
Getting AC_themes creation failed

### ISSUE THREAD

**Issue by arthuragnar** [inclusive-design/AChecker#59]
While installing Acheker I am getting 
![image](https://cloud.githubusercontent.com/assets/10372078/26051748/c0826406-3980-11e7-8763-17435e1c5a59.png) . 
I had installed it earlier on wamp and it was working file but now I have **reinstalled wamp**. Getting the attached error.

**Comment by cindyli** [comment]
Can you check the PHP and mysql versions carried by the reinstalled wamp. AChecker currently only supports up to PHP 5 and MySQL extension. It doesn't support the new MySQLi and PDO_MySQL provided by MySQL database.

**Comment by arthuragnar** [comment]
PHP version: 5.6.25
MySQL version: 5.7.14

**Comment by arthuragnar** [comment]
Resolved the issue. 
I have to manually import the database. While importing language_text.sql got error: TABLE  `language_text` does not exist. So, In language_text.sql  commented  out line 2: i.e #DROP TABLE `language_text`;
